name: autoformat
on: push
jobs:
  format-html-css-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: black (python formatter)
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .

      - name: prettier (html, css, js, md formatter)
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md,html,css} --tab-width 4
